import { Inter } from "next/font/google";
import "./globals.css";
import { CardsProvider } from "./context/CardContext";
import { UsersProvider } from "./context/UserContext";
import { AuthProvider } from "./context/AuthContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${inter.className}`}>
        {" "}
        <AuthProvider>
          <UsersProvider>
            <CardsProvider>{children}</CardsProvider>
          </UsersProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
